name: Terraform Deploy - QA

on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - qa

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  TF_VAR_resource_group_name: ${{ vars.TF_VAR_resource_group_name }}
  TF_VAR_location: ${{ vars.TF_VAR_location }}
  TF_VAR_storage_account_name: ${{ vars.TF_VAR_storage_account_name }}
  TF_VAR_environment: ${{ vars.TF_VAR_environment }}
  TF_VAR_owner: ${{ vars.TF_VAR_owner }}

jobs:
  terraform-qa:
    name: Terraform QA
    runs-on: ubuntu-latest
    environment: qa

    defaults:
      run:
        working-directory: environments/qa

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.5"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      # Solo aplica en push a qa, no en PRs
      - name: Terraform Apply
        if: github.ref == 'refs/heads/qa' && github.event_name == 'push'
        run: terraform apply -auto-approve
